### ISSUE TITLE
Polyicon Server in Docker

### ISSUE THREAD

**Issue by steirico** [ilikerobots/fontello#66]
Hi,

are there any hints or experiences on how to run Polycon server in Docker?

Following the instructions in [INSTALL.md](https://github.com/ilikerobots/polyicon/blob/fluttericon/INSTALL.md) while cloning https://github.com/ilikerobots/polyicon.git instead of https://github.com/fontello/fontello.git leads to the following error:

```bash
# ./server.js
/polyicon/lib/system/runner.js:118
  async function execute() {
        ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/polyicon/server.js:12:3)
```

Thanks

**Comment by ilikerobots** [comment]
Sorry, I haven't tried with docker yet.  Only hints I can give are that I'm currently running it with node 13.12.0 and with the following options:

```sh
export NODE_OPTIONS=--max_old_space_size=4096
./server.js
```
